### ISSUE TITLE
Merge programs with identical ID from INA LD and INA PA into one URI

### ISSUE THREAD

**Issue by Siliam** [MeMAD-project/rdf-converter#7]
Size up the problem (how many such instances) and the different causes (misspellings, added symbols etc) and use either LD or PA's URI as a reference (/use sameAs ?)

**Comment by rtroncy** [comment]
We probably need some concrete examples. My understanding is that there are some programs, defined in both INA LD and INA PA, sharing the same local ID, which have slightly different titles, or collection names, and since those are use for generating the URI identifying the programs, this results in different URIs yet identifying the same program (but from the point of view of LD or PA).

Let's first estimate how many of those cases we have and whether reconciliation (with `owl:sameAs`) is the right thing to do, versus hacking directly the way the URI is generated
