### ISSUE TITLE
Adding Flow identifiers (of media) in the knowledge graph

### ISSUE THREAD

**Issue by Siliam** [MeMAD-project/rdf-converter#9]

**Comment by rtroncy** [comment]
In order to get the Flow identifier for a media file, one needs to use the Flow search API (https://platform.limecraft.com/api/)

Example:
- The INA filename 5266001_001.ts has for identifier in Flow 808274
- The permalink for Flow for this media will be https://platform.limecraft.com/production/2336/mo/808274 where the construction involves the collection ID (2336 = MeMAD) and the Media Object ID (808274)
- The JSON view of this link is https://platform.limecraft.com/api/production/2336/mo/808274 (just add api in the URI) ... it requires a valid token to be dereferencable
